---
- hosts: localhost
  become_user: rosedu
  become: yes

  tasks:
#  - name: Install ansible_pull settings
#    become_user: root
#    become: yes
#    roles:
#      - ansible_pull

  - name: Create mascor_ws/src directory
    file: path={{ ansible_env.HOME }}/mascor_ws/src state=directory 

  - name: Clone ur repository
    git:
      repo: 'git@git.fh-aachen.de:maskor/rosin/ur.git'
      dest: '{{ ansible_env.HOME }}/mascor_ws/src/ur'
      force: yes
      recursive: no
      accept_hostkey: yes
      update: yes
      version: master
    register: ur

  - name: Update _external components of ur repository
    shell: rosws update
    args:
      chdir:  '{{ ansible_env.HOME }}/mascor_ws/src/ur/_external'
    when: ur is changed

  - name: Build workspace
    shell: catkin build
    args:
      chdir:  '{{ ansible_env.HOME }}/mascor_ws/'
    when: ur is changed

