---
- hosts: localhost
  become_user: ubuntuvm
  become: yes

  tasks:
  - name: Clone robotiq repository
    git:
      repo: 'https://github.com/nlimpert/robotiq.git'
      dest: '{{ ansible_env.HOME }}/robotiq'
      force: yes
      recursive: no
      accept_hostkey: yes
      update: yes
    register: robotiq

    #  - name: Create crontab entry to clone/pull git repository
    #    template: src=templates/testfile.j2 dest={{ ansible_env.HOME }}/Desktop/testfile owner=root group=root mode=0644

  - name: remove file from desktop
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/Desktop/testfile"

